@baseUrl = http://localhost:8080
@jwtToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6ZyIsImlhdCI6MTczNTYyOTk1NX0.cIQH0gMaEGZFKr0x0AydVmx98KepdVFgfwpqVDdn5uA

### GET request to example server
POST {{baseUrl}}/auth/login

{
"userName": "zg",
"password": "zg1234"
}

### GET request to example server
POST {{baseUrl}}/api/manager/info

{
}

###
POST {{baseUrl}}/auth/register

{
"userName": "zg",
"password": "zg123"
}

###
POST {{baseUrl}}/auth/change

{
"userName": "zg",
"password": "zg123",
"newPassword": "zg1234"
}



### GET request to example server
GET {{baseUrl}}/api/business/demo
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{}
###