@baseUrl = http://localhost:8080
@jwtToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNjE1MzYyN30.ufrkgjzKtW12GXBp-IA3T89fGcyVQ3O_2Nl8tMH_04Y

### GET request to example server
POST {{baseUrl}}/auth/login

{
"username": "admin",
"password": "adminP"
}

### GET request to example server
POST {{baseUrl}}/api/manager/info
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
}

###
POST {{baseUrl}}/auth/register

{
"username": "admin",
"password": "adminP"
}

###
POST {{baseUrl}}/auth/change

{
"username": "admin",
"password": "adminT",
"newPassword": "adminP"
}




### 创建 app
POST {{baseUrl}}/api/applications/create
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "appName": "demoApp2",
  "showName": "OpenTP测试使用"
}

### 查询 app 列表
GET {{baseUrl}}/api/applications/
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

###
GET {{baseUrl}}/api/connections/?appKey=5eadfdc9bb22437f8cd3b49d9777d35a
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

###
GET {{baseUrl}}/api/thread-pools/?ipAndPid=127.0.0.1-73671
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

###
GET {{baseUrl}}/api/thread-pools/tp1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "ipAndPid": "127.0.0.1-73671"
}