### POST create user
POST http://10.253.52.32:8080/apps/create
Content-Type: application/json

{
  "appKey": "opentp-test"
}


### GET Apps
GET http://10.253.52.32:8080/apps


### Delete appKey
DELETE http://10.253.52.32:8080/apps/opentp-test

###