server:
  port: 9999
opentp:
  servers: 10.253.52.34:9527
  appKey: opentp-client-springBoot
  appSecret: 123456
  reconnect:
    initial-Delay: 5
    period: 5
  export:
    initial-delay: 2
    period: 2